apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: podinfo
  namespace: test
spec:
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: podinfo
  canaryAnalysis:
    interval: 15s
    maxWeight: 50
    metrics:
    - interval: 1m
      name: request-success-rate
      threshold: 99
    - interval: 30s
      name: request-duration
      threshold: 500
    stepWeight: 5
    threshold: 5
    webhooks:
    - metadata:
        cmd: curl -sd 'test' http://podinfo-canary:9898/token | grep token
        type: bash
      name: acceptance-test
      timeout: 30s
      type: pre-rollout
      url: http://flagger-loadtester.test/
    - metadata:
        cmd: hey -z 1m -q 10 -c 2 http://podinfo-canary.test:9898/
      name: load-test
      timeout: 5s
      url: http://flagger-loadtester.test/
  progressDeadlineSeconds: 60
  service:
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    hosts:
    - app.sebastianbernheim.com
    port: 9898
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
